version: '3.8'

services:
  qlhs-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: qlhs-server:${version}
    volumes:
      - FileStorage:/app/FileStorage
    ports:
      - "7014:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    # command: ${command}
volumes:
  FileStorage:


