version: '3.8'

services:
  qlhs-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: qlhs-server:${version}
    volumes:
      - ./FileStorage:/path/in/container/FileStorage
    ports:
      - "5014:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    # command: ${command}
    


